version: '3.1'

services:
  mongo1:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
    - 9042:9042
    - 27017:27017
    volumes:
      - ./data/data1:/data/db
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
